name: compiler
version: 0.0.1
synopsis: Simple compiler for PA037 course
license: MIT
author: Jan Tojnar
maintainer: jtojnar@gmail.com
category: Language

executables:
  compiler:
    main: Main.hs
    dependencies:
      - base >=4.10 && <4.14
      - hashmap >= 1.3 && < 1.4
      - llvm-hs >= 9.0 && < 9.1
      - megaparsec >= 8.0 && < 8.1
      - optparse-applicative
      - text
    source-dirs: src

tests:
  test:
    source-dirs:
      - tests
      - src
    main: test.hs
    dependencies:
      - base
      - HUnit >= 1.6 && < 1.7
      - megaparsec
      - tasty >= 1.0 && < 1.3
      - tasty-hunit >= 0.10 && < 0.11
      - text
