name: compiler
version: 0.0.1
synopsis: Simple compiler for PA037 course
license: MIT
author: Jan Tojnar
maintainer: jtojnar@gmail.com
category: Language

executables:
  compiler:
    main: Main.hs
    dependencies:
      - base
      - compiler
      - filepath
      - llvm-hs-pretty >= 0.9 && < 0.10
      - megaparsec
      - optparse-applicative
      - text

library:
  dependencies:
    - base >=4.10 && <4.14
    - containers
    - hashmap >= 1.3 && < 1.4
    - llvm-hs >= 9.0 && < 9.1
    - llvm-hs-pure >= 9.0 && < 9.1
    - megaparsec >= 8.0 && < 8.1
    - mtl >= 2.2 && < 2.3
    - text
  source-dirs: src

tests:
  test:
    source-dirs: tests
    main: Spec.hs
    dependencies:
      - base
      - compiler
      - hashmap
      - megaparsec
      - hspec >= 2.7 && < 2.8
      - text
