name: CI

on:
  pull_request:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Nix
      uses: cachix/install-nix-action@v11

    - name: Build and run tests
      run: nix-build
